module.exports = {
    edge2x: 'app-portfolio-card[id="ausu"] div span[class="mat-button-wrapper"]',
    ed2ge2XsiteOption: '//app-portfolio-card[@id="bullring"]//button[contains(@class, "mat-focus-indicator")]//span[@class="mat-button-wrapper"][contains(text(),"Edge2x ")]',
    today: '//div[contains(text(),"Today")]',
    assertPredection: '//div[contains(text(),"Prediction unavailable")]',
    tomorrow: '//div[contains(text(),"Tomorrow")]',
    assertTommorrow: '//div[contains(text(),"Prediction unavailable")]',
    analytics: '//div[contains(text(),"Analytics")]',
    assertReview: '//div[contains(text(),"REVIEW")]',
    assertShowMe: '//div[contains(text(),"SHOW ME")]',
    assertSpecificDayOrWeek: '//div[contains(text(),"Specific day or week")]',
    assertDaysLike: '//div[contains(text(),"Days like...")]',
    assertConditionsLike: '//div[contains(text(),"Conditions like...")]',
    assertDayComparisons: '//div[contains(text(),"Day comparisons...")]',
    assertBuildYourOwnQuery: '//div[contains(text(),"BUILD YOUR OWN QUERY")]',
    assertLaunchQueryBuilding: '//button[@id="queryBuilderPageButton"]',
    assertAnalytics: '//div[contains(text(),"Analytics")]',
    assertArrow: '//mat-icon[contains(text(),"north")]',
    assertOpacity: '//mat-icon[contains(text(),"opacity")]',
    assertOutsideTemperatureWindow: '//div[contains(text(),"OUTSIDE TEMPERATURE (°C)")]',
    assertSpaceTemperature: '//div[contains(text(),"SPACE TEMPERATURE (°C)")]',
    assertComfort: '//div[contains(text(),"COMFORT (%)")]',
    assertSingleChartCompareMode: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-map-page[1]/div[1]/div[2]/div[1]/div[1]/button[1]',
    keyBoardArrowLeft: '//mat-icon[contains(text(),"keyboard_arrow_left")]',
    date12: '//div[contains(text(),"12")]',
    date18: '//div[contains(text(),"18")]',
    assertDate12: '//span[contains(text(),"12/09/2022")]',
    assertDate19: '//span[contains(text(),"19/09/2022")]',
    keyboardBackSpace: '//mat-icon[contains(text(),"keyboard_backspace")]',
    clickOnExpandMoreButton: '//mat-icon[contains(text(),"expand_more")]',
    assertJanuaryMonth: '//div[contains(text(),"JAN")]',
    assertYears: '//div[contains(text(),"2020")]',
    assertCalendar: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-map-page[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/app-map-left-panels[1]/div[1]/mat-accordion[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[1]/div[3]/app-date-range-picker[1]/mat-calendar[1]/div[1]',
    clickOnExpandLess: '//mat-icon[contains(text(),"expand_less")]',
    assertDayLikeCalender: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-show-me-days[1]/div[1]/div[1]/div[1]/div[1]/div[2]/app-date-picker[1]/mat-calendar[1]/div[1]/mat-month-view[1]/table[1]',
    assertAllDaysLike: '//div[contains(text(),"Show me all days like DD/MM/YYYY")]',
    clickOnConditionsLikeFeature: '//div[contains(text(),"Conditions like...")]',
    assertOutsideTemperature: '//div[contains(text(),"‘Show me mornings where outdoor temperature was ab")]',
    clickOnOutsideTemperature: '//span[contains(text(),"Outside Temperature")]',
    assertMorningBar: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[1]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]',
    assertAfternoonBar: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[1]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]',
    assertEveningBar: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[1]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]',
    assertNightBar: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[1]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]',
    assertResetButton: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]',
    assertShowDays: '#submitButton',
    clickOnSpaceTemperature: '//span[contains(text(),"Space Temperature")]',
    assertMorningText: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[2]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]',
    assertAfternoonText: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[2]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]',
    assertEveningText: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[2]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]',
    assertNightText: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[2]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]',
    clickOnComfort: '//span[contains(text(),"Comfort")]',
    assertComfortMorning: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[3]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]',
    assertComfortAfternoon: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[3]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]',
    assertComfortEvening: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[3]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]',
    assertComfortNight: '//body/app-root[1]/div[1]/div[2]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/div[2]/app-conditions-like[1]/div[1]/div[1]/div[1]/div[1]/div[4]/mat-accordion[1]/div[3]/app-conditions-like-panel[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]',
    clickOnDayComparisonsButton: '//div[contains(text(),"Day comparisons...")]',
    assert10DaysToCompareText: '//span[contains(text(),"Select up to 10 days to compare")]',
    dayOne: '.highcharts-point-hover',
    //edge2x: '.mat-focus-indicator > .mat-button-wrapper',
    timeLine: '.mat-slider[role="slider"]',
    assertTimeLine: '.mat-slider',
    playButton: 'app-map-slider-buttons > .d-flex > :nth-child(2) > .mat-icon',
    restartButton: '.d-flex > :nth-child(1) > .mat-icon',
    fastRewind: ':nth-child(1) > .h-100 > .mat-icon',
    assertDatesOnTimeLine: ':nth-child(6) > .mapSliderDateLabel',
}